title: HTMLQuickStart
description: HTML을 3시간 만에 배우기 위한 프로젝트
baseurl: "/HTMLQuickStart"
url: "data-jeong.github.io"
theme: minima
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    #line_numbers: true
    line_format: "%i"
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

plugins:
  - jekyll-mermaid
